### ISSUE TITLE
Code of conduct (pdf)

### ISSUE THREAD

**Issue by sammyar23** [sammyar23/Sprint1#3]
As a requirement for sprint one, we are supposed to follow & a code of conduct in order to participate in the group if members of the group failed to follow the code of conduct, a disciplinary action would follow.

**Comment by youniselwahai1** [comment]
As part of the requirement of sprints one, we were supposed to follow a code of conduct protocol as a group in order to avoid any issues which could be faced within a group. If the group members do not participate by signing the documentation, they would be disqualified for participating in the group however, according to our plan, all members of the group have by signing the documentation and one of the member of the group to complete the documentation who in this case is called Younis.

**Comment by youniselwahai1** [comment]
If any team member in the group require any assistance, all understanding that they would be able to go on the roehampton website and open Moodle and locate the file on software engineering week 2 seminar, which would give you a full breakdown. If students need any further request regarding the requirements that is needed for them to participate in the group, they are able to speak to the group Manager which would be able to take it further if any assistance is required please do not hesitate.
